name: Compile JOSS Paper Draft
on:
  push:
    paths:
      - 'paper.md'
      - 'paper.bib'
      - 'system_architecture.png'
  pull_request:
    paths:
      - 'paper.md'
      - 'paper.bib'
      - 'system_architecture.png'
  workflow_dispatch:

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Build JOSS Paper PDF
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: paper.md

      - name: Upload compiled paper PDF
        uses: actions/upload-artifact@v4
        with:
          name: paper-pdf
          path: paper.pdf
